// THIS FILE WAS GENERATED BY bridge.view AND SHOULD NOT BE MODIFIED

library templates_2015_08_11_18_05_34_133;

import "package:bridge/view.dart";
import 'package:jaded/runtime.dart';
import 'package:jaded/runtime.dart' as jade;

@proxy
class Templates extends TemplateCollection {
  Map<String, TemplateGenerator> get templates => {
    "app": () async => new Template(parsed: """${

    await (locals) async {
  if (locals == null) locals = {};
  
var buf = [];
var self = locals;
if (self == null) self = {};
buf.add("<!DOCTYPE html><html lang=\"en\"><head><title>Bridge</title><script src=\"//use.typekit.net/dcz8uda.js\"></script><script>try {\n    Typekit.load();\n} catch (e) {}</script><style>${await $include('example-styles')}</style></head><body><div class=\"wrap-all\"><div class=\"wrap-row\"><div class=\"wrap-cell\">${$block( 'content')}</div></div></div></body></html>");;
return buf.join("");

}(data)}
""", data: data),
    "error": () async => new Template(parsed: """${await $extends('app', {'content': """
  <h3>
    ${message == null ? 'Oops! Something went wrong!' : message}
    ${await (() async => (code != 200 && code != null) ? """
      <small>($code)</small>
    """ : "")()}</h3>

  
  ${await (() async => (Environment.isDevelopment && stackTrace != null) ? """
    <h6>$exception</h6>
    <pre class='stack-trace'>${$escape($instantiate(#Chain.forTrace, stackTrace).terse.toString())}</pre>
  """ : "")()}"""})}""", data: data),
    "example-styles": () async => new Template(parsed: """body, html, .wrap-all {
    height:100%;
    width:100%;
    margin:0;
    padding:0;
    background-color: #f4f4f4;
    font-family: 'aktiv-grotesk-std', Helvetica, sans-serif;
    font-size: 1.2em;
}
img {
    max-width: 10em;
    box-sizing: border-box;
    padding:0 1em;
    width:100%;
}
.wrap-all {
    display: table;
}
.wrap-row {
    display: table-row;
}
.wrap-cell {
    display: table-cell;
    vertical-align: middle;
    text-align: center;
}
iframe {
    display: inline-block;
    margin: auto;
    width: 3.25em;
    padding-top: 0.2em;
    vertical-align: bottom;
}
.stack-trace {
    font-size: 0.5em;
    white-space: pre-wrap;
    text-align: left;
    max-width: 70em;
    margin: auto;
    background: #fbfbfb;
    padding:1em;
}""", data: data),
    "index": () async => new Template(parsed: """${await $extends('app', {'content': """
  <div>
    <img src="http://dart-bridge.github.io/images/logo-blue.svg" alt="Bridge">
  </div>
  <iframe src="https://ghbtns.com/github-btn.html?user=dart-bridge&repo=framework&type=star&count=true"
          frameborder="0" scrolling="0" height="20px"></iframe>
  <iframe src="https://ghbtns.com/github-btn.html?user=dart-bridge&repo=framework&type=watch&count=true&v=2"
          frameborder="0" scrolling="0" width="170px" height="20px"></iframe>
"""})}""", data: data),
  };
}