name: app
version: 0.1.0
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  bridge: 
    git:
      url: https://github.com/dart-bridge/framework
      ref: feature/chalk-templates
dev_dependencies:
  test: any
  grinder: any
