name: app
version: 0.1.0
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  bridge: 
    git:
      url: https://github.com/dart-bridge/framework
      ref: develop 
  unsafe_extension: 0.0.18
  libffi6_extension: 0.0.6
dev_dependencies:
  test: any
  grinder: any

# Temporary (https://github.com/dart-lang/pub/issues/1341)
transformers:
- $dart2js:
    $exclude: web/**.dart
