# [bridge.http]

# HTTP Server options
server:
  # Set this property to 80 to bind to the public port.
  # Requires administrator capabilities (sudo).
  port: 1337
  host: localhost

  public_root: web
  build_root: storage/.build

  use_ssl: false
  ssl:
    # If this port is the same as server.port, or not included at all
    # then there won't be any HTTP to HTTPS redirects set up.
    port: 1337

    certificate: storage/certificate.pem
    private_key: storage/key.pem
    password: env(SSL_PRIVATE_KEY_PASSWORD)